### ISSUE TITLE
How spectra was run on Bassez dataset

### ISSUE THREAD

**Issue by mxposed** [dpeerlab/SpectraReproducibility#1]
Thank you for this reproducibility repo and the promising & interesting Spectra package!

I could not find the code that was used to run Spectra on the Bassez dataset in this repo, only to reproduce figures from already computed h5ad objects and other model outputs. Did I miss it?

I am particularly interested in which gene sets & other parameters were supplied to the Spectra model and which cell type annotations were used. Additionally, in the [Supplemental table 1](https://www.biorxiv.org/content/10.1101/2022.12.20.521311v1.supplementary-material) where the gene sets are, you have e.g. both `CD8_T` and `CD8-T` (with dash and with underscore), which is confusing as to which sets the model saw.

**Comment by wallet-maker** [comment]
Hi, 

If you want to reproduce the results from the paper, you have to use the development version of Spectra:

The relevant files are in the util directory of this repo (I have added a couple of files which should make this easier):

- `util.py` contains the process_Bassez function which you can use to obtain the relevant variables (you have to adjust the paths)
- `pyspade_global.py` is the development version of the algorithm, you can launch it with run_spade_all_global.py

You can also run the version in the [github.com/dpeerlab/spectra](url) repo which you can run with lambda=0.01, delta=0.001, rho 0.001 and otherwise defaults.  It will result in highly similar results. The genesets in the default dictionary used by spectra are identical with the ones we used in the paper. Note that for many findings we use offset = 0 to generate the marker genes, this output can be retrieved from the model file. 

Regarding the Supplementary Table 1 this was refering to our Knowledge Base. But some annotations were still in the old format (note that this is a spreadsheet exported for the paper and was not used as an input for the model). The gene sets the model saw are under [github.com/spectra/annotations.json](url) I have also added the relevant .csv files in the utils directory of this repo.

Let me know if that helps.

Thanks,
Thomas

**Comment by mxposed** [comment]
Thank you very much.
I still could not find where you harmonize the cell type labels between Bassez et al annotations and gene set keys for input to Spectra.
Everything else looks great, this is very helpful!

**Comment by wallet-maker** [comment]
Hi,
as discussed the annotations we used for running Spectra are from our relabeled data and are identical to the keys in the dictionary under github.com/dpeerlab/spectra/annotations.json .

Thanks,
Thomas
